### ISSUE TITLE
Occasional freezes if apply page colors enabled for toolbar

### ISSUE THREAD

**Issue by zezic** [nt1m/vivaldi-fox#118]
For Firefox 89.0 this addon introduces freezes when switching between some tabs if the "apply page colors" option enabled for toolbar. Other than that it works fine.

**Comment by zezic** [comment]
As a workaround I disabled the "apply page colors" for toolbar, set its opacity to 0 and added the next rule to my `userChrome.css` to keep icons and active tab text readable:
```css
#nav-bar,
.tabbrowser-tab[visuallyselected="true"]:-moz-lwtheme {
  color: var(--lwt-toolbar-field-color) !important;
}
```
